name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

#    - name: Create the Package
#      run: dotnet pack --configuration Release

#    - name: Publish Nuget
#      run: dotnet nuget push "Fynance/bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }}  --skip-duplicate --source "https://api.nuget.org/v3/index.json"
